# Generated by Django 5.0.4 on 2024-08-14 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='access_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
